sudo: required

language: minimal

services:
  - docker

before_script:
  # this install.sh script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_API_KEY" | docker login --username _ --password-stdin registry.heroku.com

script:
  - docker build -t $APP_NAME .

deploy:
  - provider: script
    script: sh scripts/deploy_docker.sh $APP_NAME "$DOCKER_USERNAME"
    skip_cleanup: true
  - provider: script
    script: 
      sh scripts/deploy_docker.sh $APP_NAME/web registry.heroku.com
      heroku container:release web --app $APP_NAME
    skip_cleanup: true

env:
  global:
    - APP_NAME=tinkoff-budget
